# Generated by Django 5.1.2 on 2024-12-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultation_alter_dossier_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_dossier', to='api.dossier'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='bilanBiologique',
            field=models.ManyToManyField(blank=True, related_name='sejour_bilanBio', to='api.bilanbiologique'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='bilanRadiologique',
            field=models.ManyToManyField(blank=True, related_name='sejour_bilanRadio', to='api.bilanradiologique'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='consultation',
            field=models.ManyToManyField(blank=True, related_name='cons_dossier', to='api.consultation'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='ordannance',
            field=models.ManyToManyField(blank=True, related_name='sejour_ord', to='api.ordonnance'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='medicaments',
            field=models.ManyToManyField(blank=True, related_name='ordonnances', to='api.medicament'),
        ),
    ]
