# Generated by Django 5.1.2 on 2024-12-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resume_remove_consultation_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='medcin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medi_ord', to='api.medcin'),
        ),
    ]
