# Generated by Django 5.1.2 on 2024-12-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordonnance_medcin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='medcin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medi_ord', to='api.medcin'),
        ),
    ]
