# Generated by Django 5.1.2 on 2024-12-31 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patient_have_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dateAdmission',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
