# Generated by Django 5.1.2 on 2025-01-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dossier_dateadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labo_bilan', to='api.laborantin'),
        ),
    ]
