# Generated by Django 5.1.2 on 2025-01-01 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_bilanbiologique_laborantin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='date_prescription',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='date_prescription',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medcalrecord',
            name='parametre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medcalrecord',
            name='unite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medcalrecord',
            name='value',
            field=models.FloatField(blank=True),
        ),
    ]
