# Generated by Django 5.1.2 on 2025-01-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bilanbiologique_date_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcalrecord',
            name='unite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medcalrecord',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
