# Generated by Django 5.1.2 on 2025-01-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bilanbiologique_status_bilanradiologique_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labo_bilan', to='api.laborantin'),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_bilan', to='api.radiologue'),
        ),
    ]
