# Generated by Django 5.1.2 on 2025-01-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_bilanbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='medcin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medcin_bilanBio', to='api.medcin'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='medcin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medcin_bilanRad', to='api.medcin'),
        ),
    ]
