# Generated by Django 5.1.2 on 2025-01-03 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bilanbiologique_medcin_bilanradiologique_medcin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dateMaj',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dateSortie',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
