# Generated by Django 5.1.2 on 2025-01-03 18:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dossier_datemaj_dossier_datesortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('tension', models.FloatField(default=0.0)),
                ('frequanceCardiaque', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='mesures',
            new_name='mesuresPrises',
        ),
        migrations.RenameField(
            model_name='soin',
            old_name='observation',
            new_name='descriptionSoin',
        ),
        migrations.AddField(
            model_name='consultation',
            name='raison_admission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='trouveDiagnostic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='consul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cons_resum', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='soin',
            name='typeSoin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='soin',
        ),
        migrations.AddField(
            model_name='consultation',
            name='soin',
            field=models.ManyToManyField(related_name='soin_sejour', to='api.soin'),
        ),
    ]
