# Generated by Django 5.0.4 on 2025-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_observation_rename_mesures_resume_mesuresprises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qrcode',
            field=models.CharField(default='', max_length=15),
        ),
    ]
