# Generated by Django 5.0.4 on 2025-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_patient_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='en_cours_traitement',
            field=models.BooleanField(default=False),
        ),
    ]
