# Generated by Django 5.0.4 on 2025-01-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_bilanradiologique_medcin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='medcin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medcin_bilanRad', to='api.medcin'),
        ),
    ]
