# Generated by Django 5.0.4 on 2025-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_bilanradiologique_medcin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='images',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
