# Generated by Django 5.0.4 on 2025-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_bilanradiologique_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
