# Generated by Django 5.0.4 on 2025-01-04 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_bilanradiologique_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='soin',
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateProchaineCons',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consultation',
            name='soins',
            field=models.ManyToManyField(related_name='consultations', to='api.soin'),
        ),
        migrations.AddField(
            model_name='soin',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medcin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.medcin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='raison_admission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='soin',
            name='typeSoin',
            field=models.CharField(max_length=30),
        ),
    ]
