# Generated by Django 5.0.4 on 2025-01-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_consultation_soin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soin',
            old_name='typeSoin',
            new_name='subject',
        ),
    ]
