# Generated by Django 5.0.4 on 2025-01-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_soin_infirmier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soin',
            old_name='descriptionSoin',
            new_name='description',
        ),
    ]
