# Generated by Django 5.0.4 on 2025-01-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_descriptionsoin_soin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medcin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medcin'),
        ),
    ]
