# Generated by Django 5.0.4 on 2025-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_consultation_medcin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='soins',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='api.soin'),
        ),
    ]
