# Generated by Django 5.0.4 on 2025-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_consultation_soins'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='dateValidation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
