# Generated by Django 5.0.4 on 2025-01-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_ordonnance_datevalidation_ordonnance_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='dateValidation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
